---
- name: Install and configure Zabbix Agent2 on Rocky Linux and Ubuntu
  hosts: testcore
  become: true
  gather_facts: true

  pre_tasks:
    - name: Verify that the OS is either Rocky Linux or Ubuntu
      debug:
        msg: "Supported OS detected: {{ ansible_distribution }} (version {{ ansible_distribution_version }})"
      when: ansible_distribution | lower in ['rocky', 'ubuntu']

    - name: Abort play if unsupported OS
      meta: end_play
      when: ansible_distribution | lower not in ['rocky', 'ubuntu']

  tasks:
    ####################################################################
    # Tasks for Rocky Linux
    ####################################################################
    - name: "Rocky Linux | Check if /etc/yum.repos.d/epel.repo exists"
      stat:
        path: /etc/yum.repos.d/epel.repo
      register: epel_repo_stat
      when: ansible_distribution | lower == "rocky"

    - name: "Rocky Linux | Add 'excludepkgs=zabbix*' to /etc/yum.repos.d/epel.repo if not present"
      lineinfile:
        path: /etc/yum.repos.d/epel.repo
        insertafter: '^\[epel\]'
        line: "excludepkgs=zabbix*"
        state: present
      when:
        - ansible_distribution | lower == "rocky"
        - epel_repo_stat.stat.exists

    - name: "Rocky Linux | Install Zabbix repository RPM"
      yum:
        name: "https://repo.zabbix.com/zabbix/7.0/rocky/9/x86_64/zabbix-release-latest-7.0.el9.noarch.rpm"
        state: present
      when: ansible_distribution | lower == "rocky"

    - name: "Rocky Linux | Clean DNF cache"
      command: dnf clean all
      when: ansible_distribution | lower == "rocky"

    - name: "Rocky Linux | Install Zabbix Agent2 package"
      yum:
        name: zabbix-agent2
        state: present
      when: ansible_distribution | lower == "rocky"

    - name: "Rocky Linux | Start and enable Zabbix Agent2 service"
      systemd:
        name: zabbix-agent2
        state: restarted
        enabled: true
      when: ansible_distribution | lower == "rocky"

    ####################################################################
    # Tasks for Ubuntu
    ####################################################################
    - name: "Ubuntu | Set Zabbix repository DEB URL based on Ubuntu version"
      set_fact:
        zabbix_repo_deb: >-
          {% if ansible_distribution_version.startswith('24.04') %}
          https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_7.0+ubuntu24.04_all.deb
          {% elif ansible_distribution_version.startswith('22.04') %}
          https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_7.0+ubuntu22.04_all.deb
          {% else %}
          https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_7.0+ubuntu22.04_all.deb
          {% endif %}
      when: ansible_distribution | lower == "ubuntu"

    - name: "Ubuntu | Download Zabbix repository DEB package"
      get_url:
        url: "{{ zabbix_repo_deb }}"
        dest: /tmp/zabbix-release.deb
      when: ansible_distribution | lower == "ubuntu"

    - name: "Ubuntu | Install Zabbix repository DEB package"
      apt:
        deb: /tmp/zabbix-release.deb
        state: present
      when: ansible_distribution | lower == "ubuntu"

    - name: "Ubuntu | Update APT cache"
      apt:
        update_cache: yes
      when: ansible_distribution | lower == "ubuntu"

    - name: "Ubuntu | Install Zabbix Agent2 package"
      apt:
        name: zabbix-agent2
        state: present
      when: ansible_distribution | lower == "ubuntu"

    - name: "Ubuntu | Start and enable Zabbix Agent2 service"
      systemd:
        name: zabbix-agent2
        state: restarted
        enabled: true
      when: ansible_distribution | lower == "ubuntu"
